### ISSUE TITLE
all.csv is not available from the ShapeNetV1PointCloud.zip

### ISSUE THREAD

**Issue by csjxchen** [ethz-asl/3dsnet#3]

**Comment by mattiasegu** [comment]
Hey @csjxchen , thanks for pointing this out! I updated the README with information on where to find the file. Apparently, the download link on the original shapenet website doesn't work as of now. I uploaded a version of the `all.csv` at [this link](https://drive.google.com/drive/folders/18OxvcDcCoxAfypU0zDrhsnCA4yXG_NRL?usp=sharing), you can use this one.

**Comment by csjxchen** [comment]
Thanks for your reply. It's a great help for  me.
