### ISSUE TITLE
DataSize of training samples

### ISSUE THREAD

**Issue by csjxchen** [ethz-asl/3dsnet#4]
Hi, Thanks for your wonderful code and it's helpful for me.
But, I feel uncertain in detail when conduct experiments:  
In your paper 3DSnet subsection 4.4, it said that the number of armchair and straight chair is  1995 and 1974 respectively while i got the size are 794 and 1240 in practice. （I download the experiment data from the link offered in download_shapenet_pointclouds.sh)
Wish your reply soon!

**Comment by mattiasegu** [comment]
Hmm, there's a mismatch in the number of items per class reported in the taxonomy viewer and the real number of items in the all.csv.

According to taxonomy viewer: 'armchair' (1974), 'straight' (1995).
According to all.csv (from which we get modelId and parse chairs from the dataset):  'armchair' (1052), 'straight' (1555).

Is it possible that in your count you are considering only training samples? Nevertheless, this count should be corrected also in the paper.

----------------------------

For reference, you can see the [taxonomy.json](https://shapenet.org/resources/data/shapenetcore.taxonomy.json) here and find the name for the desired class, e.g. 'armchair' --> 02738535. Then, remove leading 0 --> 2738535 and look for the modelId in the [all.csv](https://shapenet.cs.stanford.edu/shapenet/obj-zip/SHREC16/all.csv). If you want to know the number of samples available across all splits (train, val, test), just count the samples with the desired modelId.

Let me know if this addresses your question.

**Comment by csjxchen** [comment]
Thanks for your reply! It does address my question.
